#!/bin/sh
set -eu
if uname -o | grep -q Msys && command -v pwsh.exe >/dev/null 2>&1; then
	command -v pwsh.exe
elif command -v getent >/dev/null 2>&1; then
	getent passwd "$(whoami)" | cut -d: -f7
elif command -v perl >/dev/null 2>&1; then
	perl -e '@x=getpwuid($<); print $x[8]'
else
	command -v sh
fi
