inputs:
  timeout:
    type: number
    default: 60

runs:
  using: composite
  steps:
    - shell: sh
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TIMEOUT: ${{ inputs.timeout }}
      run: |
        "$GITHUB_ACTION_PATH/start"
