#!/bin/sh
set -eu

# Detect `sudo`
SUDO=
if command -v sudo >/dev/null 2>&1; then
	SUDO=sudo
fi

# Parse platform & arch
case $(uname -o) in
	Darwin)
		PLATFORM=darwin ;;
	Linux|GNU/Linux)
		PLATFORM=linux ;;
	Msys)
		PLATFORM=windows ;;
esac
case $(uname -m) in
	aarch64|arm64) ARCH=arm64 ;;
	amd64|x86_64) ARCH=amd64 ;;
esac

# Someone dumped `nvm.sh` into `.bash_profile` on the Ubuntu GitHub action runner, which prevents
# `.profile` from being loaded. But `.profile` is where the distribution puts all its nice color
# settings.
if [ -f ~/.bash_profile ] && ! grep -qv nvm.sh ~/.bash_profile; then
	cat ~/.bash_profile >> ~/.profile
	rm ~/.bash_profile
fi

# Install dependencies
case "$PLATFORM" in
	linux)
		# Linux[alpine]
		if command -v apk >/dev/null 2>&1; then
			echo ::group::Install dependencies[apk] - console
			$SUDO apk add bind-tools curl jq openssh
			echo ::endgroup::
		fi

		# Linux[arch]
		if command -v pacman >/dev/null 2>&1; then
			echo ::group::Install dependencies[arch] - console
			$SUDO pacman -Syu --noconfirm bind curl jq openssh
			echo ::endgroup::
		fi

		# Linux[debian/ubuntu]
		if command -v apt-get >/dev/null 2>&1; then
			APT_PACKAGES='curl dnsutils jq ssh'
			# shellcheck disable=SC2086
			if dpkg --get-selections $APT_PACKAGES 2>&1 | grep -qv 'install$'; then
				# We ~probably~ have these installed, so run a quick test to maybe skip `apt-get update`
				echo ::group::Install dependencies[apt] - console
				$SUDO apt-get -qq update
				$SUDO apt-get -qq install -y $APT_PACKAGES
				echo ::endgroup::
			fi
		fi

		# Linux[redhat]
		if command -v yum >/dev/null 2>&1; then
			echo ::group::Install dependencies[yum] - console
			$SUDO yum -q install -y bind-utils curl-minimal jq openssh-clients
			echo ::endgroup::
		fi
		;;
esac

# Add `bin` to PATH
PATH="$GITHUB_ACTION_PATH/bin:$GITHUB_ACTION_PATH/upterm/${PLATFORM}_${ARCH}:$PATH"
export PATH

# Locate shell, apply motd
MOTD_TOKENS="X:${GITHUB_REPOSITORY##*/}
Y:$GITHUB_TRIGGERING_ACTOR"
SH=$(shell/locate-shell)
shell/apply-motd "$SH" "$MOTD_TOKENS" <kraftwerk.motd

# authorized_keys
mkdir -p ~/.ssh
curl -H "Authorization: Bearer $GITHUB_TOKEN" -fsSL \
	"https://api.github.com/users/$GITHUB_TRIGGERING_ACTOR/keys" | \
	jq -r '.[] | .key' >> ~/.ssh/authorized_keys

# Setup upterm keys
if [ ! -f ~/.ssh/upterm ]; then
	ssh-keygen -q -t ed25519 -N '' -f ~/.ssh/upterm
fi
UPTERM_HOST=uptermd.upterm.dev
UPTERM_IP=
if command -v dig >/dev/null 2>&1; then
	UPTERM_IP=$(dig +short "$UPTERM_HOST")
elif command -v nslookup >/dev/null 2>&1; then
	UPTERM_IP=$(nslookup "$UPTERM_HOST" 2>/dev/null | grep -Eo '([0-9]+\.){3}[0-9]+' | tail -n1)
fi
if [ -n "$UPTERM_IP" ]; then
	ssh-keyscan $UPTERM_HOST 2>/dev/null | \
		sed "s/$UPTERM_HOST/@cert-authority $UPTERM_HOST,$UPTERM_IP/" \
		>> ~/.ssh/known_hosts
fi
ssh-keyscan "$UPTERM_IP" 2>/dev/null >> ~/.ssh/known_hosts

# Socket paths are named based on current pid, so we know where to find them easily.
# On Windows we can't rename it, so instead the file will contain a location
SOCKET_PATH_LINK=~/.upterm-socket-$$

# Not needed but just a reminder. `upterm` will not overwrite an existing socket environment
# variable which can be very confusing during development of this tool.
unset UPTERM_ADMIN_SOCKET

# Start daemonized upterm
# nb: `pwsh.exe` does not support contracted `-il` argument, so make sure to use `-i -l` instead.
# You also shouldn't need the `-i` flag since the shell should detect the pty but it sometimes
# doesn't work, and doesn't hurt to add otherwise.
REMOTE_COMMAND="$SH -i -l"
case "$REMOTE_COMMAND" in
	# Trampoline off `sh` first which does a better job of picking up terminal features.
	*pwsh.exe*) REMOTE_COMMAND="sh -c \"exec $REMOTE_COMMAND\""
esac
if [ "$PLATFORM" = windows ]; then
	# shellcheck disable=SC2016
	LOCAL_COMMAND='ln -s "$(wslpath "$UPTERM_ADMIN_SOCKET")" "'"$SOCKET_PATH_LINK"'"; tail -f /dev/null'
else
	# shellcheck disable=SC2016
	LOCAL_COMMAND='ln -s "$UPTERM_ADMIN_SOCKET" "'"$SOCKET_PATH_LINK"'"; tail -f /dev/null'
fi
nohup upterm host \
	--accept \
	--authorized-keys ~/.ssh/authorized_keys \
	--private-key ~/.ssh/upterm \
	--force-command "$REMOTE_COMMAND"  \
	-- sh -c "$LOCAL_COMMAND" &
UPTERM_PID=$!
trap 'kill $UPTERM_PID || true' EXIT

# Wait for upterm admin socket
STARTED=$(date +%s)
while [ ! -e "$SOCKET_PATH_LINK" ] && [ $(($(date +%s) - STARTED)) -lt 2 ]; do sleep 0.1; done
USOCKET=$(readlink "$SOCKET_PATH_LINK")
rm -f "$SOCKET_PATH_LINK"
if [ ! -e "$USOCKET" ]; then
	echo "Failed to start upterm host"
	exit 1
fi

# Wait for first client
STARTED=$(date +%s)
while [ $(($(date +%s) - STARTED)) -lt "$TIMEOUT" ]; do
	if upterm session current --admin-socket "$USOCKET" | grep -q 'Connected Client'; then break; fi
	sleep 1
done

# Wait for connections to drain
PREVIOUS=0
while upterm session current --admin-socket "$USOCKET" 2>/dev/null | grep -q 'Connected Client'; do
	if [ $(($(date +%s) - PREVIOUS)) -gt 60 ]; then
		echo "$(date)" - Someone is connected...
		PREVIOUS=$(date +%s)
	fi
	if [ -f ~/.continue-workflow ]; then
		rm -f ~/.continue-workflow
		trap - EXIT
		break
	fi
	sleep 1
done
